# Generated by Django 4.2.30 on 2026-07-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TabState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.CharField(db_index=True, max_length=20, unique=True)),
                ('options', models.JSONField(default=dict)),
                ('mutcd_map', models.JSONField(default=dict)),
                ('mutcd_to_class', models.JSONField(default=dict)),
                ('mutcd_word_fallback', models.JSONField(default=dict)),
                ('mutcd_reverse_map', models.JSONField(default=dict)),
                ('type_map', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='TabRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab', models.CharField(db_index=True, max_length=20)),
                ('tab_record_id', models.PositiveIntegerField()),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['tab_record_id'],
                'indexes': [models.Index(fields=['tab', 'tab_record_id'], name='inventory_t_tab_69dd02_idx')],
                'unique_together': {('tab', 'tab_record_id')},
            },
        ),
    ]
