# Generated by Django 4.2.30 on 2026-07-19 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySection',
            fields=[
                ('key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('configuration', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='MutcdMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_description', models.CharField(max_length=500)),
                ('mutcd_code', models.CharField(blank=True, max_length=200)),
                ('classification', models.CharField(blank=True, max_length=300)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutcd_mappings', to='inventory.inventorysection')),
            ],
            options={
                'ordering': ['section', 'word_description'],
            },
        ),
        migrations.CreateModel(
            name='MutcdFallback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('word_description', models.CharField(max_length=500)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutcd_fallbacks', to='inventory.inventorysection')),
            ],
            options={
                'ordering': ['section', 'code'],
            },
        ),
        migrations.CreateModel(
            name='MutcdClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('classification', models.CharField(max_length=300)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutcd_classifications', to='inventory.inventorysection')),
            ],
            options={
                'ordering': ['section', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DropdownOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropdown_options', to='inventory.inventorysection')),
            ],
            options={
                'ordering': ['section', 'field_name', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AutoFillMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_value', models.CharField(max_length=500)),
                ('values', models.JSONField(default=dict)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_fill_mappings', to='inventory.inventorysection')),
            ],
            options={
                'ordering': ['section', 'driver_value'],
            },
        ),
        migrations.AddConstraint(
            model_name='mutcdmapping',
            constraint=models.UniqueConstraint(fields=('section', 'word_description'), name='unique_section_mutcd_word'),
        ),
        migrations.AddConstraint(
            model_name='mutcdfallback',
            constraint=models.UniqueConstraint(fields=('section', 'code'), name='unique_section_mutcd_fallback'),
        ),
        migrations.AddConstraint(
            model_name='mutcdclassification',
            constraint=models.UniqueConstraint(fields=('section', 'code'), name='unique_section_mutcd_class'),
        ),
        migrations.AddConstraint(
            model_name='dropdownoption',
            constraint=models.UniqueConstraint(fields=('section', 'field_name', 'value'), name='unique_section_field_option'),
        ),
        migrations.AddConstraint(
            model_name='autofillmapping',
            constraint=models.UniqueConstraint(fields=('section', 'driver_value'), name='unique_section_auto_fill_driver'),
        ),
    ]
