# Generated by Django 5.2.15 on 2026-07-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_tabrecord_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
