# Generated by Django 5.2.15 on 2026-07-28 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_tabrecord_display_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProcessedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_type', models.CharField(db_index=True, max_length=20)),
                ('frame_number', models.CharField(blank=True, max_length=100)),
                ('latitude', models.CharField(blank=True, max_length=50)),
                ('longitude', models.CharField(blank=True, max_length=50)),
                ('elevation', models.CharField(blank=True, max_length=50)),
                ('image_path', models.TextField(blank=True)),
                ('code', models.CharField(max_length=200)),
                ('raw_data', models.JSONField(default=dict)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_processed_records', to='inventory.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_processed_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['project', 'inventory_type', 'id'], name='inventory_ai_project_type_idx')],
            },
        ),
    ]
