# Generated by Django 5.2.15 on 2026-07-28 08:49

from django.db import migrations


def move_ai_rows_into_sign_inventory(apps, schema_editor):
    AIProcessedRecord = apps.get_model("inventory", "AIProcessedRecord")
    TabRecord = apps.get_model("inventory", "TabRecord")
    next_id = max(
        TabRecord.objects.filter(tab="sign").values_list("tab_record_id", flat=True),
        default=0,
    )
    project_orders = {}
    for source in AIProcessedRecord.objects.order_by("id").iterator():
        next_id += 1
        if source.project_id not in project_orders:
            project_orders[source.project_id] = max(
                TabRecord.objects.filter(project_id=source.project_id, tab="sign")
                .values_list("display_order", flat=True),
                default=0,
            )
        project_orders[source.project_id] += 1
        raw = source.raw_data or {}
        text_value = str(raw.get("TEXT", "") or "").strip()
        data = {
            "LATITUDE": source.latitude,
            "LONGITUDE": source.longitude,
            "MUTCD": source.code,
            "WORD_DESCRIPTION": "" if text_value.upper() == "NULL" else text_value,
            "FRAME": source.frame_number,
            "AI_LATITUDE": source.latitude,
            "AI_LONGITUDE": source.longitude,
            "TIME": str(raw.get("TIME", "") or ""),
            "X1": str(raw.get("X1", "") or ""),
            "Y1": str(raw.get("Y1", "") or ""),
            "X2": str(raw.get("X2", "") or ""),
            "Y2": str(raw.get("Y2", "") or ""),
            "ELEVATION": source.elevation,
            "IMAGE": source.image_path,
            "_AI_PROCESSED": True,
            "_AI_SOURCE_FILE": source.source_file,
        }
        TabRecord.objects.create(
            project_id=source.project_id,
            owner_id=None,
            tab="sign",
            tab_record_id=next_id,
            display_order=project_orders[source.project_id],
            data=data,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_aiprocessedrecord'),
    ]

    operations = [
        migrations.RunPython(move_ai_rows_into_sign_inventory, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='AIProcessedRecord',
        ),
    ]
