# Generated by Django 5.2.15 on 2026-07-28 09:00

from django.db import migrations


def backfill_ai_coordinates(apps, schema_editor):
    TabRecord = apps.get_model("inventory", "TabRecord")
    for record in TabRecord.objects.filter(tab="sign").iterator():
        data = record.data or {}
        if not data.get("_AI_PROCESSED"):
            continue
        changed = False
        if "AI_LATITUDE" not in data:
            data["AI_LATITUDE"] = data.get("LATITUDE", "")
            changed = True
        if "AI_LONGITUDE" not in data:
            data["AI_LONGITUDE"] = data.get("LONGITUDE", "")
            changed = True
        if changed:
            record.data = data
            record.save(update_fields=["data"])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_delete_aiprocessedrecord'),
    ]

    operations = [
        migrations.RunPython(backfill_ai_coordinates, migrations.RunPython.noop),
    ]
