# Generated by Django 5.2.15 on 2026-07-28 10:25

import django.db.models.deletion
from django.db import migrations, models


def initialize_ai_filter_configuration(apps, schema_editor):
    Project = apps.get_model("inventory", "Project")
    TabRecord = apps.get_model("inventory", "TabRecord")
    AIImportSettings = apps.get_model("inventory", "AIImportSettings")
    AIObservedCode = apps.get_model("inventory", "AIObservedCode")
    for project in Project.objects.iterator():
        AIImportSettings.objects.get_or_create(
            project_id=project.pk,
            defaults={"excluded_codes": ["NULL", "NOT SIGN", "OTHER"]},
        )
        counts = {}
        for record in TabRecord.objects.filter(project_id=project.pk, tab="sign").iterator():
            data = record.data or {}
            if not data.get("_AI_PROCESSED"):
                continue
            code = str(data.get("MUTCD", "") or "").strip().upper()
            if code:
                counts[code] = counts.get(code, 0) + 1
        AIObservedCode.objects.bulk_create([
            AIObservedCode(project_id=project.pk, code=code, occurrence_count=count)
            for code, count in counts.items()
        ])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_backfill_ai_coordinates'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIImportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluded_codes', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_import_settings', to='inventory.project')),
            ],
            options={
                'verbose_name_plural': 'AI import settings',
            },
        ),
        migrations.CreateModel(
            name='AIObservedCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('occurrence_count', models.PositiveIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_observed_codes', to='inventory.project')),
            ],
            options={
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('project', 'code'), name='unique_project_ai_observed_code')],
            },
        ),
        migrations.RunPython(initialize_ai_filter_configuration, migrations.RunPython.noop),
    ]
