# Generated by Django 5.2.15 on 2026-07-28 11:23

import django.db.models.deletion
from decimal import Decimal, InvalidOperation
from django.conf import settings
from django.db import migrations, models


def backfill_ai_frame_metadata(apps, schema_editor):
    TabRecord = apps.get_model("inventory", "TabRecord")
    pending = []
    for record in TabRecord.objects.only("pk", "data", "is_ai_processed", "ai_frame").iterator():
        data = record.data or {}
        if not data.get("_AI_PROCESSED"):
            continue
        record.is_ai_processed = True
        try:
            frame = Decimal(str(data.get("FRAME", "")).strip())
            record.ai_frame = int(frame) if frame >= 0 and frame == frame.to_integral_value() else None
        except (InvalidOperation, ValueError):
            record.ai_frame = None
        pending.append(record)
        if len(pending) >= 500:
            TabRecord.objects.bulk_update(pending, ["is_ai_processed", "ai_frame"])
            pending.clear()
    if pending:
        TabRecord.objects.bulk_update(pending, ["is_ai_processed", "ai_frame"])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_remove_legacy_ai_other_records'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameRangeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_frame', models.PositiveIntegerField()),
                ('end_frame', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['project', 'start_frame', 'end_frame', 'user__username'],
            },
        ),
        migrations.AddField(
            model_name='tabrecord',
            name='ai_frame',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='tabrecord',
            name='is_ai_processed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(backfill_ai_frame_metadata, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='tabrecord',
            index=models.Index(fields=['project', 'tab', 'is_ai_processed', 'ai_frame'], name='inventory_ai_frame_idx'),
        ),
        migrations.AddField(
            model_name='framerangeassignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_range_assignments', to='inventory.project'),
        ),
        migrations.AddField(
            model_name='framerangeassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_frame_ranges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='framerangeassignment',
            index=models.Index(fields=['project', 'user', 'start_frame', 'end_frame'], name='frame_range_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='framerangeassignment',
            constraint=models.CheckConstraint(condition=models.Q(('start_frame__lte', models.F('end_frame'))), name='frame_range_start_lte_end'),
        ),
        migrations.AddConstraint(
            model_name='framerangeassignment',
            constraint=models.UniqueConstraint(fields=('project', 'user', 'start_frame', 'end_frame'), name='unique_project_user_frame_range'),
        ),
    ]
