# Generated by Django 5.2.15 on 2026-08-15 06:14

import django.db.models.deletion
import inventory.models
from django.db import migrations, models


def seed_california_jurisdiction(apps, schema_editor):
    Jurisdiction = apps.get_model("inventory", "Jurisdiction")
    jurisdiction, _ = Jurisdiction.objects.get_or_create(
        code="us-ca",
        defaults={"country": "United States", "state": "California"},
    )
    Project = apps.get_model("inventory", "Project")
    Project.objects.filter(jurisdiction__isnull=True).update(jurisdiction=jurisdiction)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_framerangeassignment_tabrecord_ai_frame_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['country', 'state'],
                'constraints': [models.UniqueConstraint(fields=('country', 'state'), name='unique_country_state')],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='jurisdiction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='inventory.jurisdiction', verbose_name='Country / State'),
        ),
        migrations.CreateModel(
            name='MutcdReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutcd_code', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to=inventory.models.mutcd_reference_upload_to)),
                ('source_sheet', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jurisdiction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutcd_references', to='inventory.jurisdiction')),
            ],
            options={
                'ordering': ['jurisdiction', 'mutcd_code', 'description'],
                'indexes': [models.Index(fields=['jurisdiction', 'mutcd_code'], name='inventory_m_jurisdi_2ee893_idx')],
                'constraints': [models.UniqueConstraint(fields=('jurisdiction', 'mutcd_code', 'description'), name='unique_jurisdiction_mutcd_description')],
            },
        ),
        migrations.RunPython(seed_california_jurisdiction, migrations.RunPython.noop),
    ]
